version: '3.9'

name: example-api

services:
  app:
    build:
      context: ./boot
      dockerfile: Dockerfile
    container_name: boot
    restart: unless-stopped
    environment:
      SPRING_ACTIVE_PROFILE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    # TODO: Add default data and table creation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: