spring:
  application:
    name: cdn-microservice-api

  profiles:
    active: ${SPRING_ACTIVE_PROFILE:local}

  jpa:
    properties:
      hibernate:
        default_schema: public

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
