spring:
  application:
    name: example-api

  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}

  jpa:
    properties:
      hibernate:
        default_schema: public

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /api