spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cdn_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379